### ISSUE TITLE
addScenario failed 

### ISSUE THREAD

**Issue by emmaliulu** [JGCRI/rgcam#12]
My command line is 
prj <- addScenario('database_0','water_constraint.dat','Constraint0','ElecProdbyTechVint.xml')

I have the database and .xml file under the same directory, when I try to use the addScenario function, I got this error message,

Error in value[[3L]](cond) : 
  error reading file Error in file(file, "r"): cannot open the connection
In addition: Warning message:
In file(file, "r") :
  cannot open file 'C:\Users\liul564\AppData\Local\Temp\RtmpQlRUhm\file1580475e6142.csv': No such file or directory

**Comment by rplzzz** [comment]
@emmaliulu I suspect the model interface is encountering an error and not producing any results.  Can you rerun the command with the extra argument `migabble=""`?  That will cause the output from the model interface to be sent to the console.  If you could post that output here, that will help us get to the bottom of this.

**Comment by emmaliulu** [comment]
I've tried your approach. Here's what I got.

InterfaceMain: batchFile: C:\Users\liul564\AppData\Local\Temp\RtmpQlRUhm\file15803734285.xml
Running headless? true
The database is not open.
About to perform query: collection('database_0')/scenario
[Fatal Error] :4:6: The processing instruction target matching "[xX][mM][lL]" is not allowed.
org.w3c.dom.ls.LSException: The processing instruction target matching "[xX][mM][lL]" is not allowed.
	at com.sun.org.apache.xerces.internal.parsers.DOMParserImpl.parse(Unknown Source)
	at ModelInterface.ModelGUI2.DbViewer.readQueries(DbViewer.java:1398)
	at ModelInterface.ModelGUI2.DbViewer.runBatch(DbViewer.java:1887)
	at ModelInterface.InterfaceMain.runBatch(InterfaceMain.java:650)
	at ModelInterface.InterfaceMain.main(InterfaceMain.java:206)
Caused by: ::::4:6:29:The processing instruction target matching "[xX][mM][lL]" is not allowed.
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.scanPIData(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanPIData(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.scanPI(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	... 5 more
INFO; Finished running batch file
Error in value[[3L]](cond) : 
  error reading file Error in file(file, "r"): cannot open the connection
In addition: Warning message:
In file(file, "r") :
  cannot open file 'C:\Users\liul564\AppData\Local\Temp\RtmpQlRUhm\file15806e734fa2.csv': No such file or directory

**Comment by rplzzz** [comment]
So, as you can see here:
```
About to perform query: collection('database_0')/scenario
[Fatal Error] :4:6: The processing instruction target matching "[xX][mM][lL]" is not allowed.
org.w3c.dom.ls.LSException: The processing instruction target matching "[xX][mM][lL]" is not allowed.
at com.sun.org.apache.xerces.internal.parsers.DOMParserImpl.parse(Unknown Source)
at ModelInterface.ModelGUI2.DbViewer.readQueries(DbViewer.java:1398)
at ModelInterface.ModelGUI2.DbViewer.runBatch(DbViewer.java:1887)
at ModelInterface.InterfaceMain.runBatch(InterfaceMain.java:650)
at ModelInterface.InterfaceMain.main(InterfaceMain.java:206)
```
the model interface ran into some kind of problem.  @pralitp, can you tell at a glance what the problem is?

**Comment by pralitp** [comment]
@emmaliulu, could you post the query file you are trying to run?  It seems to think there is something malformed about it.

**Comment by emmaliulu** [comment]
This is my query file. Thank you.

<queries>
<aQuery>
<?xml version="1.0" encoding="UTF-8"?>
      <region name="AK"/>
      <region name="AL"/>         
      <region name="AR"/>
      <region name="AZ"/>
      <region name="CA"/>
      <region name="CO"/>
      <region name="CT"/>
      <region name="DC"/>
      <region name="DE"/>
      <region name="FL"/>
      <region name="GA"/>
      <region name="HI"/>
      <region name="IA"/>
      <region name="ID"/>
      <region name="IL"/>
      <region name="IN"/>
      <region name="KS"/>
      <region name="KY"/>
      <region name="LA"/>
      <region name="MA"/>
      <region name="MD"/>
      <region name="ME"/>
      <region name="MI"/>
      <region name="MN"/>
      <region name="MO"/>
      <region name="MS"/>
      <region name="MT"/>
      <region name="NC"/>
      <region name="ND"/>
      <region name="NE"/>
      <region name="NH"/>
      <region name="NJ"/>
      <region name="NM"/>
      <region name="NV"/>
      <region name="NY"/>
      <region name="OH"/>
      <region name="OK"/>
      <region name="OR"/>
      <region name="PA"/>
      <region name="RI"/>
      <region name="SC"/>
      <region name="SD"/>
      <region name="TN"/>
      <region name="TX"/>
      <region name="UT"/>
      <region name="VA"/>
      <region name="VT"/>
      <region name="WA"/>
      <region name="WI"/>
      <region name="WV"/>
      <region name="WY"/>

      <supplyDemandQuery title="Electricity production by technology by vintage">
         <axis1 name="region">region</axis1>
         <axis2 name="Year">physical-output[@vintage]</axis2>
         <xPath buildList="false" dataName="output" group="false" sumAll="false">*[@type = 'sector' and (@name = 'Coal-Gas Dispatch Output' or @name='electricity' or @name='elect_td_bld' or @name='industrial energy use' or @name='coal CCS retrofit')]/*[@type = 'subsector']/*[@type = 'technology']/output-primary[@type='output'(:collapse:)]/physical-output/node()</xPath>
         <comments/>
         <showAttribute attribute-name="year" level="technology"/>
      </supplyDemandQuery>

</aQuery>
</queries>

**Comment by emmaliulu** [comment]
For some reason, I cannot copy and post the region names with the rest of the query, so here they are.

<queries>
<aQuery>
      <region name="AK"/>
      <region name="AL"/>         
      <region name="AR"/>
      <region name="AZ"/>
      <region name="CA"/>
      <region name="CO"/>
      <region name="CT"/>
      <region name="DC"/>
      <region name="DE"/>
      <region name="FL"/>
      <region name="GA"/>
      <region name="HI"/>
      <region name="IA"/>
      <region name="ID"/>
      <region name="IL"/>
      <region name="IN"/>
      <region name="KS"/>
      <region name="KY"/>
      <region name="LA"/>
      <region name="MA"/>
      <region name="MD"/>
      <region name="ME"/>
      <region name="MI"/>
      <region name="MN"/>
      <region name="MO"/>
      <region name="MS"/>
      <region name="MT"/>
      <region name="NC"/>
      <region name="ND"/>
      <region name="NE"/>
      <region name="NH"/>
      <region name="NJ"/>
      <region name="NM"/>
      <region name="NV"/>
      <region name="NY"/>
      <region name="OH"/>
      <region name="OK"/>
      <region name="OR"/>
      <region name="PA"/>
      <region name="RI"/>
      <region name="SC"/>
      <region name="SD"/>
      <region name="TN"/>
      <region name="TX"/>
      <region name="UT"/>
      <region name="VA"/>
      <region name="VT"/>
      <region name="WA"/>
      <region name="WI"/>
      <region name="WV"/>
      <region name="WY"/>

</aQuery>
</queries>

**Comment by pralitp** [comment]
Ok, I think maybe there are two things going on.  Judging by the message I think it requires the heading XML heading.  Secondly the queries that rgcam will be looking to run need to be batch query syntax, for instance:
```
<queries>
   <aQuery>
       <region name="USA" />
  <supplyDemandQuery title="Electricity production by technology by vintage">
     <axis1 name="region">region</axis1>
     <axis2 name="Year">physical-output[@vintage]</axis2>
     <xPath buildList="false" dataName="output" group="false" sumAll="false">*[@type = 'sector' and (@name = 'Coal-Gas Dispatch Output' or @name='electricity' or @name='elect_td_bld' or @name='industrial energy use' or @name='coal CCS retrofit')]/*[@type = 'subsector']/*[@type = 'technology']/output-primary[@type='output'(:collapse:)]/physical-output/node()</xPath>
     <comments/>
     <showAttribute attribute-name="year" level="technology"/>
  </supplyDemandQuery>
  </aQuery>
</queries>
```

The ability to run a single query at a time has been added to `rgcam` but is still in a development branch so for now just wrap it in the batch query syntax as above.

**Comment by emmaliulu** [comment]
![xml file](https://cloud.githubusercontent.com/assets/20967190/25970829/02b43406-3668-11e7-852f-e80af230a76d.png)

For some reason, I cannot copy and paste the entire xml file here. So I took a snapshot of the file.

**Comment by pralitp** [comment]
You should be able to attach the actual file instead of putting the contents in the comment.

**Comment by pralitp** [comment]
Sorry, I should have been more explicit in my earlier post.  Could you try adding:
```
<?xml version="1.0" encoding="UTF-8"?>
```
To the top of your file and see if that helps?

**Comment by emmaliulu** [comment]
@rplzzz I was able to add the first database with your solution. However, when I tried to add additional database, it showed this error message again:

Error in value[[3L]](cond) : 
  error reading file Error in file(file, "r"): cannot open the connection
In addition: Warning message:
In file(file, "r") :
  cannot open file 'C:\Users\liul564\AppData\Local\Temp\RtmpQlRUhm\file158043b579f0.csv': No such file or directory

My command line is 
prj<-addScenario('database_1','water_constraint.dat','Constraint1','ElecProdbyTechVint.xml')
where database_1 is my additional database

**Comment by pralitp** [comment]
@emmaliulu, is there more output you can post, particularly with setting the extra argument `migabble=""` when running `addScenario`?

**Comment by emmaliulu** [comment]
@pralitp Here's what I got when I tried to add additional scenario

prj <- addScenario('database_2', 'water_constraint.dat',
+                    'Constraint2', 'ElecProdbyTechVint.xml',migabble="" )

InterfaceMain: batchFile: C:\Users\liul564\AppData\Local\Temp\Rtmp4At2rb\file16d02792a59.xml
Running headless? true
The database is not open.
About to perform query: collection('database_2')/scenario
java.lang.Exception: Could not find scenarios to run.
	at ModelInterface.ModelGUI2.DbViewer.runBatch(DbViewer.java:1877)
	at ModelInterface.InterfaceMain.runBatch(InterfaceMain.java:650)
	at ModelInterface.InterfaceMain.main(InterfaceMain.java:206)
INFO; Finished running batch file
Error in value[[3L]](cond) : 
  error reading file Error in file(file, "r"): cannot open the connection
In addition: Warning message:
In file(file, "r") :
  cannot open file 'C:\Users\liul564\AppData\Local\Temp\Rtmp4At2rb\file16d077cc57ab.csv': No such file or directory

**Comment by pralitp** [comment]
Ah, ok.  It doesn't find a scenario named "Constraint2" in the database.  Maybe it should be named something different?

Note that you can also pass in `NULL` as the scenario name argument to `addScenario` and it will just query the last scenario in the database.  Maybe this would be appropriate in your case?

**Comment by emmaliulu** [comment]
@pralitp It worked! Thank you very much!

**Comment by pralitp** [comment]
Great!
