### ISSUE TITLE
Add Scenario not working

### ISSUE THREAD

**Issue by dsills** [JGCRI/rgcam#13]
On April 28 all was well, but since yesterday the following command is not working:

```
alg <- addScenario('database_basexdb', 'Algae8.dat','NoALGAE', '../output/queries/AlgaeQueriesOld.xml')
```

I am getting the following error:

Stopped at ., 1/87:
[bxerr:BASX0000] Could not find scenarios to run.
Error in parse(text = x) : attempt to use zero-length variable name

**Comment by rplzzz** [comment]
@dsills This looks like the error message you get when the requested scenario is not in the database.  It's possible that you are pointing at the wrong database, or that when you set up the run you forgot to change the scenario title in the `configuration.xml` file.

**Comment by dsills** [comment]
Thank you, we're working on it.

== Deborah


>
