### ISSUE TITLE
Queries with XQuery Functions Failing on addScenario

### ISSUE THREAD

**Issue by michaeljaywalsh** [JGCRI/rgcam#14]
When running:
`prj <- addScenario(conn,'name00.dat', 'BIOMASS','output/queries/Q.xml')`
Where Q.xml contains a single query (aQuery) of the types noted below, copied over from Main_Queries.xml I got the following failures:

`Stopped at ., 1/2264:
[XPST0003] Expecting ']', found '&'.
Error in parse(text = x) : attempt to use zero-length variable name`

For **Primary Energy Consumption (Direct Equivalent)**,  **GHG emissions by sector**, **CH4 emissions by subsector** and **N2O emissions by subsector**

Queries w/o XQuery Functions work.

Also noted by @dsills

**Comment by pralitp** [comment]
I'm not exactly sure what is happening.  It seems these queries are getting mangled by the xml2 R package and/or the BaseX library.  At first I thought it was just the XML characters are not getting properly replaced in lines such as:
```
$scenario_name := string-join($scenario_split[position() &lt; last()], ' ',
```

But even when working around that specifically it still seems to have trouble.

For now the best workaround is to add those queries manually using the "query for a query" technique as described in the vignette:
```
query_name <- "Primary energy with CCS (Direct Equivalent)"
pri_query_query <- paste0("doc('output/queries/Q.xml')//*[@title='", query_name, "']")
examples.proj <- addSingleQuery(conn, 'name00.dat', query_name, pri_query_query,
                                'BIOMASS', c('USA'))
```

I'll keep digging to figure out where things go wrong when passing the actual query from R to BaseX.

**Comment by michaeljaywalsh** [comment]
Thanks for looking into this @pralitp 
Unfortunately the "query for a query" technique is not working for me for the XQuery Function queries. 
I tried the LUC/simple-queries-interactive.xml example from the vignette. -- That works
I tried querying from Main_queries.xml (so as not to mess anything up) -- This works for simple queries but no the XQuery Function queries (i.e. Primary energy with CCS (Direct Equivalent, N2O, CH4 etc.)

Can you confirm that running the _Primary energy..._ query in your example works on your database? 

These error out with:
`Stopped at ., 1/87:
[bxerr:BASX0000] java.lang.StringIndexOutOfBoundsException: String index out of range: -1
Error in parse(text = x) : attempt to use zero-length variable name` 
Which appear to be related to an issue @rplzzz raised Friday.

**Comment by pralitp** [comment]
Using the "query for a query" technique for primary energy with CCS seems to work just fine for me.

I'm not sure where that error message would even be coming form.  Could you turn on the model interface outputs on your "connection" to get more info out of the error?  You can do that when creating the connection:
```
conn <- localDBConn('/path/to/output', 'database', migabble=FALSE)
```
Or just change it on the connection object:
```
conn$migabble <- FALSE
```

**Comment by michaeljaywalsh** [comment]
This is what I get:

`About to perform query: collection()/scenario
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.delete(AbstractStringBuilder.java:756)
	at java.lang.StringBuilder.delete(StringBuilder.java:244)
	at ModelInterface.ModelGUI2.xmldb.RunFunctionQueryBinding.bindToQuery(RunFunctionQueryBinding.java:61)
	at ModelInterface.ModelGUI2.xmldb.XMLDB.createQuery(XMLDB.java:280)
	at ModelInterface.ModelGUI2.xmldb.XMLDB.createQuery(XMLDB.java:273)
	at ModelInterface.ModelGUI2.xmldb.XMLDB.createQuery(XMLDB.java:270)
	at ModelInterface.ModelGUI2.xmldb.RunMIQuery.runMIQuery(RunMIQuery.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.basex.query.func.JavaModuleFunc.eval(JavaModuleFunc.java:71)
	at org.basex.query.func.JavaFunction.value(JavaFunction.java:71)
	at org.basex.query.func.JavaFunction.iter(JavaFunction.java:60)
	at org.basex.query.MainModule.iter(MainModule.java:117)
	at org.basex.query.QueryContext.iter(QueryContext.java:335)
	at org.basex.query.QueryProcessor.iter(QueryProcessor.java:91)
	at org.basex.core.cmd.AQuery.query(AQuery.java:94)
	at org.basex.core.cmd.XQuery.run(XQuery.java:22)
	at org.basex.core.Command.run(Command.java:253)
	at org.basex.core.Command.execute(Command.java:99)
	at org.basex.api.client.LocalSession.execute(LocalSession.java:132)
	at org.basex.api.client.Session.execute(Session.java:36)
	at org.basex.core.CLI.execute(CLI.java:103)
	at org.basex.BaseX.<init>(BaseX.java:121)
	at org.basex.BaseX.main(BaseX.java:42)
Stopped at ., 1/87:
[bxerr:BASX0000] java.lang.StringIndexOutOfBoundsException: String index out of range: -1
Parsed with column specification:
cols()
Error in parse(text = x) : attempt to use zero-length variable name`

**Comment by pralitp** [comment]
Ok, this looks like a separate bug where an empty region list was supposed to query all regions.  The code that finalizes the `XQuery` style queries doesn't cope with this.  I've clearly missed some step when I added this feature but I'm not completely sure what that is.  I'll start a separate issue to deal with this one.

In the mean time to get back to the original bug.  Could you try to run with an explicit list to see if that is at least working for you?
```
test.proj <- addSingleQuery(conn, "test.proj", query_name, pri_query_query, c(), c("USA", "Canada"))
```

**Comment by michaeljaywalsh** [comment]
Yeah, including the region list works now...sorry about missing that...so this is working now

**Comment by michaeljaywalsh** [comment]
So for now I'm just going to incorporate the query for query into our workflow. This actually saves me from having to maintain two query files and just allows me to focus on using the queries for each separate investigation I have.

**Comment by pralitp** [comment]
So, I just realized what is going on: BaseX recognizes the text with in the `<xPath>` tags of the query as `XQuery` syntax and attempts to run it before passing it to the model interface.  However the context of that syntax would then be illegal (and the Model Interface needs to fill in some information such as scenarios and regions).
It seems the appropriate thing to do all along would have been to enclose that text in [CDATA tags](https://en.wikipedia.org/wiki/CDATA) (Note XML tags such as `&lt;`, `&amp;`, etc should be written as `<`, `&`, etc within CDATA tags) :

```
<supplyDemandQuery title="Building Floorspace per capita">
         <axis1 name="Floorspace">input[@name]</axis1>
         <axis2 name="Year">demand-physical[@vintage]</axis2>
         <xPath buildList="true" dataName="percapita floorspace" group="false" sumAll="false">
             <![CDATA[
                     declare function local:append-heirarchy($parent as node(), $append as node()) as node() {
                         let $scn := $parent/ancestor::scenario,
                              $rgn := $parent/ancestor::region,
                             $consumer := $parent/ancestor::gcam-consumer
                           return
                              document { element scenario {
                                                $scn/@*,
                                                element region {
                                                    $rgn/@*,
                                                    element gcam-consumer {
                                                        $consumer/@*,
                                                        $append
                                                    }
                                                }
                                            }
                            }
                     };  
                     declare function local:get-percapita($inputs as node()*) as node()* {
                     unordered {    
                     for $input in $inputs
                     let $new_input :=  
                     element input {
                         attribute type {'input'},
                         attribute name { $input/@name },
                         for $demand in $input/floorspace
                         return 
                             element demand-physical {
                             attribute vintage {$demand/@year},
                             (: TODO: hard coding units :)
                             attribute unit { 'm^2/person'},
                             (: floorspace is billion m^2 and population is 1000 people and we want m^2/persion :)
                             text { $demand/text() div $input/ancestor::gcam-consumer/subregional-population[@year=$demand/@year] * 1000000 }
                         }
                     },
                     $new_root := local:append-heirarchy($input/parent::*/parent::*, $new_input)
                     return $new_root//text()
                     } 
                     };
                     declare function local:run-get-percapita($scenarios as xs:string*, $regions as xs:string*, $collection as xs:string) as node()* {     
                     let $regionsG := if(not($regions[1] = 'Global'))
                              then $regions
                              else distinct-values(collection($collection)/scenario/world/*[@type='region']/@name)
                     return
                     for $scenario in $scenarios,       
                     $region in $regionsG   
                     let $scenario_split := tokenize($scenario, ' '),       
                     $scenario_name := string-join($scenario_split[position() < last()], ' '),
			 	 	 $scenario_date := $scenario_split[last()],
			 	 	 $currTree := collection($collection)/scenario[@name = $scenario_name and @date = $scenario_date]/world/*[@type = 'region' and @name=$region]
                     return 
                        local:get-percapita($currTree/gcam-consumer//building-node-input)
                        
         }; 
                 local:run-get-percapita((:scenarios:), (:regions:), (:collection:))
                 ]]>
            </xPath>
         <comments/>
      </supplyDemandQuery>
```

You can fix up your batch files with the CDATA tags and they should work just fine.  In terms of closing this issue I'm not sure what the right approach is.  Fixing up the queries seems like the obvious approach however everyone will have queries of their own which wouldn't get automatically fixed up.  I could try to put in extra checks and add the CDATA tags in the `rgcam` package but that seems like a kludge.  At the very least I can update the documentation.

**Comment by michaeljaywalsh** [comment]
This worked. Thanks!

Now the only thing killing batch mode is issue #15

**Comment by rplzzz** [comment]
@pralitp Trying to detect missing CDATA tags seems like a needless complication.  The design of rgcam assumes that queries are well formed.  So, we should fix up the query files that we distribute with GCAM (including the example file in the rgcam package) and mention the update to the query format in the rgcam documentation.  We should also make a note about the update in the GCAM docs.

@michaeljaywalsh I didn't realize issue #15 was causing problems in live use.  It's a pretty easy fix, so I'll see if I can knock that out during a lengthy telecon I have coming up this afternoon.

**Comment by michaeljaywalsh** [comment]
@rplzzz & @pralitp The updates all appear to be working for me and address issues #14 and #15
