### ISSUE TITLE
Add ability to list all scenarios in database

### ISSUE THREAD

**Issue by pralitp** [JGCRI/rgcam#24]
@xavier-gutierrez, points out that currently there is no way to get a list of the scenario that are available in a database via rgcam and instead have to resort to some other means (usually through an interactive MI session).  It should be easy enough to add this capability into rgcam.

**Comment by rplzzz** [comment]
Yes, this would be a useful thing to have.  Does the model interface support such an operation?

**Comment by pralitp** [comment]
Well, I was thinking this is something that could just be handled as a simple query to BaseX and we can cut the MI out of the loop on this one.  That being said I haven't actually tried it.

**Comment by rplzzz** [comment]
That sounds like a plan.  Let me know how it goes.
