### ISSUE TITLE
Query runs out of memory

### ISSUE THREAD

**Issue by calebbraun** [JGCRI/rgcam#31]
When running the query "GHG emissions by sector" for all regions, we run out of memory, giving this error:
```
[XPTY0004] RunMIQuery:runMIQuery(element(), empty-sequence(), xs:string+): GC overhead limit exceeded.
Error in saveProject(prjdata) :
  saveProject:  invalid project data object, stat=2
Calls: addScenario -> saveProject
```
Changing the memory limit in `runQuery.localDBConn()` from 2GB to 4GB solves this problem for me, but could cause trouble for 32-bit Java.

**Comment by rplzzz** [comment]
@pralitp Do we even support 32-bit Java?  I feel like everyone who has ever installed it has run into some kind of problem for which the fix is "install 64-bit Java".

**Comment by pralitp** [comment]
We don't support 32-bit java for running GCAM.  However technically you could use it for running the Model Interface / queries via rgcam.  It could very well be the case that windows folks have been getting away with running the 32-bit Java with rgcam this whole time and changing the max above 2GB would break them.  In which case we would have to figure out how to get R to run the right Java.. which should be possible but I didn't want to dive into that at the moment.

**Comment by rplzzz** [comment]
So, if we don't support 32-bit Java, then we should just up the memory limit in `runQuery.localDBConn`.  2 GB may have been a lot in 1997, but it's really not now.
