### ISSUE TITLE
Adding data to project file from .csv file causes error

### ISSUE THREAD

**Issue by calebbraun** [JGCRI/rgcam#33]
In the function `addQueryTable()`, I get an error when providing the name of a .csv file as the `qdata` parameter. I believe the line causing the error is line 65 in importmisc.R:
```
qdata <- read.csv(qdata, row.names=FALSE)
```
The value `FALSE` seems to be an invalid option for row.names, as the error I get is:
```
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  invalid 'row.names' specification
```

**Comment by pralitp** [comment]
Huh, it didn't cause any problems for me.  I currently have readr 1.0.0.  Which version do you have?

Although reading the documentation it _sound_ like `FALSE` should be a valid value.  I'm not sure what the purpose of that is anyhow.  Could you try just dropping the `row.names` argument and seeing if that works?

**Comment by bpbond** [comment]
@pralitp Note this is reference to `read.csv`, not `readr::read_csv`.

Yeah, you can't say `row.names = FALSE`. This has always been true IIRC; not sure how this line has ever executed without error.
