### ISSUE TITLE
Some queries are not working since update

### ISSUE THREAD

**Issue by cahartin** [JGCRI/rgcam#40]
The `GHG emission` queries are not working in rgcam when they are read in from an xml file.  They were working prior to the recent update.  rgcam returns an empty dataframe.

**Comment by cahartin** [comment]
1. for GHG emissions increase Java memory within rgcam source code
2. for primary energy - Pralit made a fix to the query.  @pralitp is this fix already in the GCAM 4.4?

**Comment by pralitp** [comment]
The `GHG emissions` is related to #31 which has the PR in.  The primary energy was related to #14 and I did update all the queries in GCAM at version 4.4 to be correct.
