### ISSUE TITLE
Handle queries that are too long

### ISSUE THREAD

**Issue by calebbraun** [JGCRI/rgcam#43]
Running Windows 7, I ran into a problem where the command being piped out by `runQuery()` was over the 8191 characters allowed by the shell. The command obviously failed, so the query returned no results. I was able to shorten the input query by removing a bunch of extra whitespace, and everything was fine after that.

This could likely be handled by removing extra whitespace in `runQuery()`, for example by adding `gsub("\\s+"," ",query)` below line 102 in `querymi.R`.

**Comment by rplzzz** [comment]
@calebbraun That sounds like a good plan.  Could you work on that sometime when you get a chance?
