### ISSUE TITLE
Query Policy Cost using RGCAM

### ISSUE THREAD

**Issue by RawisWar** [JGCRI/rgcam#54]
Hi 
I am trying to query the policy cost for my scenario run  using rgcam's addScenario function.
![image](https://user-images.githubusercontent.com/34580273/55570305-27f48280-56d1-11e9-9de4-040c69a8e767.png)

For the "costq.xml" I used  the following 
![image](https://user-images.githubusercontent.com/34580273/55570026-99800100-56d0-11e9-9d5f-c1210ef135ea.png)

When I run this code i get the error 

![image](https://user-images.githubusercontent.com/34580273/55570395-5d996b80-56d1-11e9-825b-7e83c22658a1.png)
Any help in rectifying this error will be greatly appreciated.

**Comment by rplzzz** [comment]
That's usually the error you get when the xpath query doesn't find anything.  Before we go digging too deep, can you verify that the cost curve option was set in the configuration file?  The line looks like this in the default configuration
```XML
		<Value name="createCostCurve">0</Value>
```
The value has to be set to 1 for the policy cost to be written into the output.

**Comment by RawisWar** [comment]
Yes, cost curve option was set to 1. See results below.
![image](https://user-images.githubusercontent.com/34580273/55571882-69d2f800-56d4-11e9-9335-08de3af2a63f.png)

**Comment by rplzzz** [comment]
@pralitp Do you have any ideas about what might be causing this?  It's going to be a few days before I have time to look into it.

**Comment by pralitp** [comment]
The cost curve queries need to process results in a very different way then any other results (they are reported into the database in a format that isn't totally amenable for querying).  In the model interface there was some special code to account for this and when we added support for `rgcam` this was overlooked.

Should be fairly straightforward to fix, I'll open a PR hopefully this afternoon.

**Comment by rplzzz** [comment]
@RawisWar The new version should fix your problem.  Let us know if it doesn't.
