### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by gokuliyer** [JGCRI/rgcam#57]
I got this error with install_github('JGCRI/rgcam').

ERROR: hard-coded installation path: please report to the package maintainer and use '--no-staged-install'
* removing 'C:/Users/iyer786/Documents/R/win-library/3.6/rgcam'
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/iyer786/AppData/Local/Temp/RtmpY3Wk5N/file23e42e241503/rgcam_0.5.0.tar.gz’ had non-zero exit status

Any clue what might be happening?

**Comment by pralitp** [comment]
From:
https://developer.r-project.org/Blog/public/2019/02/14/staged-install/index.html

It seems the install process in R has changed such that packages get installed in a temporary space then moved into place later.  Thus as discussed in the `Paths hard-coded in R code` section of the link above:
> With staged install, it may happen that the saving of the directory is executed when the package still runs in the temporary installation directory, typically while the package is being prepared for lazy loading. The preparation for lazy loading involves sourcing all R files of the package, hence also executing all the assignments to global variables.

We have a few of these including `DEFAULT.MICLASSPATH`, `SAMPLE.GCAMDB`, `SAMPLE.QUERIES`.  It seems converting these to functions (i.e. `getSampleGCAMDB`) is sufficient to avoid the pitfall introduced by staged installs.
