### ISSUE TITLE
RGCAM package issues

### ISSUE THREAD

**Issue by tjstelmach** [JGCRI/rgcam#80]
Hi rgcam team,
Our collaborators had a recent error related to parsing the database that was R package-related. When the `addScenario()` command was run, the following was output:
`Scenario GCAMC does not exist in this project. Creating.`
`Scenario GCAMCAN_pr does not exist in this project. Creating.`
`Scenario GCAMCAN_prov_Ref does not exist in this project. Creating.`
`Scenario MB does not exist in this project. Creating.`
`Warning message: 1: One or more parsing issues, see problems() for details`
`2. 2 failed to parse`

For reference, the only scenario being ran here is GCAMCAN_prov_Ref, yet multiple non-existent scenarios were output during parsing. Additionally, the resulting output tables had erroneous outputs that included a mix of both scenario names and data (i.e. this screenshot): 
![rgcam_error2](https://user-images.githubusercontent.com/98051493/153928107-42a1819a-fe83-46b9-bc78-ae484f394451.png)

This error was resolved by adjusting the version of readr (from 2.1.0 to 1.4.0) through modifying a renv lock file. Just wanting to flag this for future users who run into this conflict.

**Comment by tjstelmach** [comment]
Resolved by editing hte rversion of readr from 2.1.0 to 1.4.0 using renv lock file change

**Comment by nurf004** [comment]
> Resolved by editing the version of readr from 2.1.0 to 1.4.0 using renv lock file change

Hi, I'm wondering how to do this? I have no idea of using renv lock file change. Thank you!

**Comment by rongqizhu** [comment]
I have the same problem as you, but an error occurrs during installating readr 1.4.0 [https://github.com/tidyverse/readr/issues/1547]
It seems to be a problem with BH package, could you please tell me the version of the R package you used?

thanks a lot!!!
